### ISSUE TITLE
dailyuploads.net doesn't work anymore

### ISSUE THREAD

**Issue by abhiinos111abhi** [idoenk/maknyos-autoin#4]
dailyuploads.net download page auto refreshes and not working correctly.. maybe they have changed something in the website.

**Comment by p1nkyy** [comment]
Also in suprafiles. Maknyos will just make it go crazy, reloading over and over, without giving us chance to click captcha. @idoenk

**Comment by p1nkyy** [comment]
bump @idoenk

**Comment by idoenk** [comment]
This should be patched ya. maapin for loooooooooong respond. :|

thx

**Comment by p1nkyy** [comment]
Gpp bro!
BTW suprafiles masih error tapi.
