### ISSUE TITLE
False claim of production stage @ greasyfork

### ISSUE THREAD

**Issue by DFNCTSC** [idoenk/maknyos-autoin#5]
@idoenk This was true in the past, but the greasyfork script hasn't been updated in over 150 days, since October 2017, whereas the script on here was updated just 2 weeks ago.

Greasyfork script version: 3.9.40
Github script version: 3.9.41

You could at least remove the false note on the README.md that production stage is at greasyfork. 

Regardless, thanks for the script.<3

**Comment by idoenk** [comment]
Sorry for late respond,.
There's still a slow development in order to patch most of host that compatible for this script.
Version script on this repo is higher indeed, it is prep'ed for next version in GF.
Please be patient. Thx.

**Comment by idoenk** [comment]
v3.9.41 released & published on Greasyfork.

check it out. Thx :)
